export const FETCH_TOTAL_RESULT_BY_TIME = 'FETCH_TOTAL_RESULT_BY_TIME';
export const FETCH_TOTAL_RESULT_BY_TIME_SUCCESS = 'FETCH_TOTAL_RESULT_BY_TIME_SUCCESS';
export const FETCH_TOTAL_RESULT_BY_TIME_FAIL = 'FETCH_TOTAL_RESULT_FAIL';